import json
import os
import re
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

def merge_mappings(json_path):
    web_dir = "d:/advait aai/sanskrit-website-ads-main"
    db_path = os.path.join(web_dir, "database.js")
    
    if not os.path.exists(json_path):
        print(f"Error: Mappings JSON not found at {json_path}")
        return
    if not os.path.exists(db_path):
        print(f"Error: database.js not found at {db_path}")
        return
        
    with open(json_path, 'r', encoding='utf-8') as jf:
        custom_mappings = json.load(jf)
        
    with open(db_path, 'r', encoding='utf-8') as df:
        db_content = df.read()
        
    # Extract JSON string from SCRIPTURE_DB = { ... };
    json_match = re.search(r'const SCRIPTURE_DB = (\{.*\});', db_content, re.DOTALL)
    if not json_match:
        print("Error: Could not extract SCRIPTURE_DB from database.js")
        return
        
    db_json = json.loads(json_match.group(1))
    scriptures = db_json.get('scriptures', [])
    if not scriptures:
        print("Error: Empty scriptures in database")
        return
        
    charaka = scriptures[0]
    adhyayas = charaka.get('adhyayas', [])
    
    merged_count = 0
    for key, custom_audio_path in custom_mappings.items():
        # Key format: scriptureId_chapterNum_shlokaNum
        parts = key.split("_")
        if len(parts) == 3:
            scripture_id, ch_num_str, sh_num_str = parts
            ch_num = int(ch_num_str)
            sh_num = int(sh_num_str)
            
            # Find the chapter and shloka in database
            adhyaya = next((a for a in adhyayas if a.get('number') == ch_num), None)
            if adhyaya:
                shloka = next((s for s in adhyaya.get('shlokas') == sh_num), None)
                # Wait, syntax fix: next((s for s in adhyaya.get('shlokas') if s.get('number') == sh_num), None)
                shloka = next((s for s in adhyaya.get('shlokas') if s.get('number') == sh_num), None)
                if shloka:
                    # Modify the audio path in the database.js
                    paths = custom_audio_path if isinstance(custom_audio_path, list) else [custom_audio_path]
                    copied_paths = []
                    for idx, path in enumerate(paths):
                        raw_filename = os.path.basename(path)
                        src_audio = os.path.join(web_dir, "assets", "raw_audio", f"ch{ch_num}", raw_filename)
                        
                        # Use part suffix if multiple parts exist
                        if len(paths) > 1:
                            dest_filename = f"ch{ch_num}_sh{sh_num}_part{idx+1}.ogg"
                        else:
                            dest_filename = f"ch{ch_num}_sh{sh_num}.ogg"
                            
                        dest_audio = os.path.join(web_dir, "assets", "audio", dest_filename)
                        
                        # Copy file to permanent audio assets
                        if os.path.exists(src_audio):
                            os.makedirs(os.path.dirname(dest_audio), exist_ok=True)
                            import shutil
                            shutil.copy(src_audio, dest_audio)
                            copied_paths.append(f"assets/audio/{dest_filename}")
                            
                    if copied_paths:
                        shloka['audio'] = ",".join(copied_paths)
                        merged_count += 1
                        
    # Write back SCRIPTURE_DB to database.js
    new_db_js = f"// Charaka Samhita Complete Database\n// Auto-generated by parser (Merged custom mappings)\n\nconst SCRIPTURE_DB = {json.dumps(db_json, ensure_ascii=False, indent=2)};\n\nif (typeof module !== 'undefined' && module.exports) {{\n  module.exports = SCRIPTURE_DB;\n}}\n"
    
    with open(db_path, 'w', encoding='utf-8') as f:
        f.write(new_db_js)
        
    print(f"Successfully merged {merged_count} custom audio mappings permanently into database.js!")

if __name__ == '__main__':
    # Usage: python merge_custom_mappings.py path/to/mappings.json
    if len(sys.argv) < 2:
        print("Usage: python merge_custom_mappings.py <path_to_mappings_json>")
    else:
        merge_mappings(sys.argv[1])
