const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 8080;
const PUBLIC_DIR = __dirname;
const DB_PATH = path.join(PUBLIC_DIR, 'database.js');

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.ogg': 'audio/ogg',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.svg': 'image/svg+xml'
};

const server = http.createServer((req, res) => {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Handle Save Mapping API Endpoint
  if (req.method === 'POST' && req.url === '/api/save-mappings') {
    let body = '';
    req.on('data', chunk => {
      body += chunk.toString();
    });
    
    req.on('end', () => {
      try {
        const mappings = JSON.parse(body);
        
        // 1. Write the mappings to assets/auto_audio_mappings.json
        const mappingsPath = path.join(PUBLIC_DIR, 'assets', 'auto_audio_mappings.json');
        fs.writeFileSync(mappingsPath, JSON.stringify(mappings, null, 2), 'utf-8');
        
        // 2. Read database.js and update the SCRIPTURE_DB object
        if (fs.existsSync(DB_PATH)) {
          let dbContent = fs.readFileSync(DB_PATH, 'utf-8');
          const jsonMatch = dbContent.match(/const SCRIPTURE_DB = (\{.*\});/s);
          
          if (jsonMatch) {
            const dbJson = JSON.parse(jsonMatch[1]);
            const scriptures = dbJson.scriptures || [];
            
            if (scriptures.length > 0) {
              const charaka = scriptures[0];
              const adhyayas = charaka.adhyayas || [];
              
              // Iterate and update shloka audio paths
              for (const [key, val] of Object.entries(mappings)) {
                const parts = key.split('_');
                if (parts.length === 3) {
                  const [scriptureId, chNumStr, shNumStr] = parts;
                  const chNum = parseInt(chNumStr, 10);
                  const shNum = parseInt(shNumStr, 10);
                  
                  const adhyaya = adhyayas.find(a => a.number === chNum);
                  if (adhyaya) {
                    const shloka = adhyaya.shlokas.find(s => s.number === shNum);
                    if (shloka) {
                      const paths = Array.isArray(val) ? val : [val];
                      const copiedPaths = [];
                      
                      // Copy files physically and update path names
                      paths.forEach((p, idx) => {
                        const rawFilename = path.basename(p);
                        const srcAudio = path.join(PUBLIC_DIR, 'assets', 'raw_audio', `ch${chNum}`, rawFilename);
                        
                        let destFilename = '';
                        if (paths.length > 1) {
                          destFilename = `ch${chNum}_sh${shNum}_part${idx+1}.ogg`;
                        } else {
                          destFilename = `ch${chNum}_sh${shNum}.ogg`;
                        }
                        
                        const destAudio = path.join(PUBLIC_DIR, 'assets', 'audio', destFilename);
                        
                        if (fs.existsSync(srcAudio)) {
                          fs.mkdirSync(path.dirname(destAudio), { recursive: true });
                          fs.copyFileSync(srcAudio, destAudio);
                          copiedPaths.push(`assets/audio/${destFilename}`);
                        }
                      });
                      
                      if (copiedPaths.length > 0) {
                        shloka.audio = copiedPaths.join(',');
                      } else {
                        shloka.audio = '';
                      }
                    }
                  }
                }
              }
              
              // Rewrite database.js
              const updatedDbContent = `// Charaka Samhita Complete Database\n// Auto-generated by parser (Merged custom mappings)\n\nconst SCRIPTURE_DB = ${JSON.stringify(dbJson, null, 2)};\n\nif (typeof module !== 'undefined' && module.exports) {\n  module.exports = SCRIPTURE_DB;\n}\n`;
              fs.writeFileSync(DB_PATH, updatedDbContent, 'utf-8');
            }
          }
        }
        
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true, message: 'Mappings and files saved directly to disk!' }));
      } catch (err) {
        console.error('Error saving mappings:', err);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
    return;
  }

  // Static File Server
  // Clean query strings/hash parameters if any
  let cleanUrl = req.url.split('?')[0].split('#')[0];
  
  // Decode URL percent-encoded characters (like %20 for spaces)
  let decodedUrl = '';
  try {
    decodedUrl = decodeURIComponent(cleanUrl);
  } catch (e) {
    decodedUrl = cleanUrl;
  }
  
  let filePath = path.join(PUBLIC_DIR, decodedUrl === '/' ? 'index.html' : decodedUrl);

  const extname = path.extname(filePath);
  const contentType = MIME_TYPES[extname] || 'application/octet-stream';

  fs.readFile(filePath, (error, content) => {
    if (error) {
      if (error.code === 'ENOENT') {
        res.writeHead(404, { 'Content-Type': 'text/html' });
        res.end('<h1>404 Not Found</h1>', 'utf-8');
      } else {
        res.writeHead(500);
        res.end(`Server Error: ${error.code}`);
      }
    } else {
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(content, 'utf-8');
    }
  });
});

server.listen(PORT, () => {
  console.log(`\n======================================================`);
  console.log(`🚀 SANSKRIT LIBRARY SERVER ACTIVE`);
  console.log(`👉 http://localhost:${PORT}`);
  console.log(`👉 Auto-Save active: Changes save directly to disk!`);
  console.log(`======================================================\n`);
});
